# Generated by Django 5.0.14 on 2026-03-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergens',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
