# Generated by Django 5.0.14 on 2026-03-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_allergen_remove_menuitem_allergens_and_more'),
        ('users', '0002_user_allergens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allergens',
        ),
        migrations.AddField(
            model_name='user',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='users', to='menu.allergen'),
        ),
    ]
