# Generated by Django 5.0.14 on 2026-03-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_allergen_remove_menuitem_allergens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergen',
            name='category',
            field=models.CharField(choices=[('common', 'Common Allergens'), ('seafood', 'Seafood'), ('nuts', 'Nuts & Seeds'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
