# Generated by Django 5.0.14 on 2026-03-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, help_text='Order-level notes (e.g. allergies, special requests)', null=True),
        ),
    ]
